### ISSUE TITLE
add per-prover parameters

### ISSUE THREAD

**Issue by c-cube** [nunchaku-inria/logitest#2]
allow, say:

```toml

[prover]
cmd = "prover $a $b $file $timeout
a = [a1, a2, a3]
b = [b1, b2]
```

and test on the whole matrix.
